### ISSUE TITLE
convert Plots.jl -> AbstractPlotting.jl

### ISSUE THREAD

**Issue by hannahilea** [beacon-biosignals/Lighthouse.jl#1]
(transferred from https://github.com/beacon-biosignals/OldLighthouse.jl/issues/134)

> The consensus is that AbstractPlotting is easier to work with and gives you more control, and that the conversion shouldn't be too much work  -- @kolia

**Comment by ericphanson** [comment]
with the new Makie update, https://discourse.julialang.org/t/ann-makie-update-figures-and-integrated-layouts/52800, it's probably easier to do this now! Though maybe we should wait a bit first for the bugs to get worked out. (maybe @SimonDanisch can help us when the time comes too 😄).

**Comment by femtomc** [comment]
Can we revive this @SimonDanisch @hannahilea @ericphanson ? Both SeizureNet and SpikeNet are going to rely on Lighthouse for the future. Two downstream dependencies slightly elevates priority.

**Comment by femtomc** [comment]
Can you slightly raise priority level for this? @SimonDanisch @hannahilea What needs to be converted? If it's a single (relatively isolated) function to plot I can try my hand.

**Comment by ericphanson** [comment]
I think it's these functions: https://github.com/beacon-biosignals/Lighthouse.jl/blob/66cbc09977cb04f0dd6d277ce1e5db5832664b4d/src/learn.jl#L228-L428

**Comment by SimonDanisch** [comment]
I started to port  a few recipes over to BeaconPlots: https://github.com/beacon-biosignals/BeaconPlots.jl/pull/34/.
Not sure if we want to leave them there going forward, but it makes things easier for me right now.
Should be easy to move if we want them somewhere else :)

**Comment by hannahilea** [comment]
Closed as of #29!
