### ISSUE TITLE
`plot_confusion_matrix` cannot change `annotation_text_size`

### ISSUE THREAD

**Issue by abhinav3398** [beacon-biosignals/Lighthouse.jl#82]
I was trying to [increase the text size of my confusion matrix plot](https://docs.juliahub.com/Lighthouse/B1u0t/0.14.10/plotting/). But when I tried to pass in the keyword arg `annotation_text_size=34` it gave me an error. The code works fine without the keyword args (`Lighthouse.plot_confusion_matrix(rand(2, 2), ["1", "2"], :Row)`) and produces a confusion matrix plot. But when I try to change the default text size it gave me this error:
```julia
Lighthouse.plot_confusion_matrix(rand(2, 2), ["1", "2"], :Row, annotation_text_size=34)
```
```julia
MethodError: no method matching plot_confusion_matrix(::Matrix{Float64}, ::Vector{String}, ::Symbol; annotation_text_size=34)

Closest candidates are:

plot_confusion_matrix(::AbstractMatrix, ::Any, ::Any) at ~/.julia/packages/Lighthouse/K3PBy/src/learn.jl:333 got unsupported keyword argument "annotation_text_size"
```

here are my environment/system info, if it's of any help:

```Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, haswell)

Environment:
  JULIA_REVISE_WORKER_ONLY = 1
      Status `~/usr/project/dir/Project.toml`
  [ac2c24cd] Lighthouse v0.11.3
```

**Comment by abhinav3398** [comment]
haven't tried other methods yet. Let me know if it's the same with the other methods as well.

**Comment by palday** [comment]
Current Lighthouse version is 0.14.10 -- does this work when you update from v0.11.3?

**Comment by palday** [comment]
Have you restarted your Julia session? This what the referenced source line looks like now:

https://github.com/beacon-biosignals/Lighthouse.jl/blob/0540cdd5fcfc7a95cdd0b8c080febc42da736dbe/src/learn.jl#L333

The methods for `plot_confusion_matrix[!]` are defined here:

https://github.com/beacon-biosignals/Lighthouse.jl/blob/0540cdd5fcfc7a95cdd0b8c080febc42da736dbe/src/plotting.jl#L182-L184

https://github.com/beacon-biosignals/Lighthouse.jl/blob/0540cdd5fcfc7a95cdd0b8c080febc42da736dbe/src/plotting.jl#L404-L425

**Comment by abhinav3398** [comment]
> ```julia
> Lighthouse.plot_confusion_matrix(rand(2, 2), ["1", "2"], :Row, annotation_text_size=34)
> ```
restarting the session made things worse. Now i don't have any plot. Before I at least had a plot. Now instead of plot i get this as output to above code:
`FigureAxisPlot()`

**Comment by ericphanson** [comment]
That's a Makie object: https://makie.juliaplots.org/v0.17.3/documentation/plot_method_signatures/index.html#non-mutating. It should show you a plot, but you need to have a Makie backend loaded. See the Makie docs here on backends: https://makie.juliaplots.org/v0.17.3/documentation/backends/.

**Comment by abhinav3398** [comment]
Okay yup, using `WGLMakie` as a backend did the trick. But, was this mentioned in [the docs](https://docs.juliahub.com/Lighthouse/B1u0t/0.14.10/search/?q=backend) that we have to activate one of the [`Maxkie` backend](https://makie.juliaplots.org/v0.17.3/documentation/backends/)?

**Comment by ericphanson** [comment]
No, good point, we should mention it. I'll file an issue for that.
